import Foundation

/// Positive App Store review suggestions highlighting TierTap’s most useful features.
/// One is chosen at random and copied to the pasteboard when a user taps 4–5★.
enum AppStoreReviewComments {
    static let all: [String] = [
        "TierTap makes logging casino sessions effortless. Check-in is fast and I finally have clean records of every visit.",
        "The best part is tracking tier points session by session. I can actually see loyalty progress instead of guessing.",
        "Love the live session timer with Live Activity on the lock screen. I always know how long I’ve been playing.",
        "Wallet cards and tier goals are a game changer. Watching the rings fill toward the next level keeps me motivated.",
        "Analytics finally show where I earn tier points fastest. That alone is worth the download.",
        "Trips let me group sessions by Vegas weekend and see the full picture—hours, points, and results in one place.",
        "Apple Watch check-in is fantastic. I start a session from my wrist without digging out my phone.",
        "Home screen widgets keep my recent sessions and tier progress visible without opening the app.",
        "Stack tracking during table games is so useful. I know my true position without mental math.",
        "Close-out is quick and thorough—cash-out, comps, and ending tier points all in one flow.",
        "Favorite games and locations make check-in nearly instant. I’m logging sessions I used to skip.",
        "Journal and history views make it easy to find any past session. Great for reviewing a whole trip.",
        "Risk of ruin and bankroll tools help me stay disciplined. It’s more than a simple timer.",
        "Monthly Wrapped is fun and surprisingly insightful. Seeing a month of play summarized is addicting in a good way.",
        "Loyalty insights show which properties treat my play best. That’s the most useful feature for me.",
        "Dynamic Island showing my live session is polished and practical. I glance and keep playing.",
        "Comps and free play logging finally keeps my real cost of play honest.",
        "I love that I can attach photos to sessions. Great for remembering tables, machines, and trip moments.",
        "Program ladders make multi-casino loyalty less confusing. I always know what tier I’m chasing.",
        "Fast close-out for slots is perfect when I just want a clean record and to leave.",
        "Ask TierTap AI answers are surprisingly helpful for loyalty and session questions.",
        "Community feed is a nice bonus, but session logging and tier tracking are why I stay.",
        "Average bet tracking (actual vs rated) is something I couldn’t find elsewhere. Huge for serious players.",
        "The activity grid in History is a beautiful way to see how often I’m really playing.",
        "Tier rate per hour finally tells me if a session was efficient for loyalty, not just fun.",
        "Linking sessions to wallet cards auto-updates my tier. That sync feels magic after close-out.",
        "Poker, slots, and table games all supported cleanly. One app for every floor I play.",
        "Private locations plus public casino search covers home games and resorts equally well.",
        "I finally stopped using Notes app spreadsheets. TierTap replaced all of that.",
        "Session mood tracking after close-out is a thoughtful touch I didn’t know I needed.",
        "Tax prep export from history is incredibly useful at year-end. Saved me hours.",
        "The floating pill navigation keeps Check In centered—always one tap away when I sit down.",
        "Live session buy-ins and comps add up cleanly. No more lost receipts in my head.",
        "Trip prep and recap nudges help me plan and review casino weekends properly.",
        "Logging streaks keep me consistent. I actually remember to check in every visit now.",
        "Chip estimator at close-out is clever and saves time when the rack is messy.",
        "Shareable session summaries are great for group chats after a big night.",
        "Rewards program picker is thorough—my cards and properties are easy to set up.",
        "I use TierTap mainly for tier points, and it nails that better than anything else.",
        "Seeing cumulative tier points across sessions is motivating and crystal clear.",
        "Incomplete Watch sessions finish smoothly on iPhone. Cross-device flow just works.",
        "Settings are deep without being overwhelming. I customized results basis and stuck with it.",
        "Best casino session tracker I’ve tried. Fast logging plus real loyalty intelligence.",
        "The goal rings on Home make progress feel tangible every time I open the app.",
        "Map and location tools make tagging the right property painless.",
        "I love reviewing rated vs actual average bet after the fact. Eye-opening for table play.",
        "Photo feed in Journal is a fun way to scroll trip memories tied to real session data.",
        "Session calendar view helps me spot patterns in when I play and how I do.",
        "Bankroll view keeps the bigger picture honest between trips.",
        "Clean design, dark casino vibe, and features that matter to loyalty players.",
        "Check-in under fifteen seconds with presets. That’s the killer feature for me.",
        "I track M life, Caesars, and more in one wallet. Multi-program life finally organized.",
        "Live Activity plus Watch means I never lose the session clock.",
        "Closing metrics rings are a satisfying wrap after a long session.",
        "Loyalty pace insights help me decide whether another session is worth it.",
        "I appreciate responsible-gaming touches alongside serious tracking tools.",
        "Editing past sessions is easy when I forgot a buy-in or mistyped cash-out.",
        "Verified vs unverified tier points badges keep my data quality honest.",
        "Recent sessions tiles on Home get me back into details in one tap.",
        "This is the first app that treats tier points as first-class data, not an afterthought.",
        "Free play logging changed how I evaluate ‘winning’ nights. Much clearer now.",
        "Trip share cards are a fun wrap for friends after a joint casino weekend.",
        "Flight and lodging fields on trips make the whole travel plan live next to play data.",
        "Strategy and risk views add depth without pushing bad habits.",
        "I open widgets more than the app itself—progress at a glance is perfect.",
        "Session art and share flows are delightful, but logging accuracy is why I recommend it.",
        "The app understands casino players: buy-ins, comps, tiers, and time on device.",
        "Quick denomination buttons at close-out make cash-out entry painless.",
        "I finally know my true hours on property across a whole trip.",
        "Favorite presets mean I’m logging even short slots sessions I used to ignore.",
        "Analytics date chips (7/30/90) make short- and long-term trends easy to compare.",
        "Tier goal celebrations on Watch are a fun little dopamine hit after grinding points.",
        "Private notes on sessions help me remember table dynamics and machine feel.",
        "I switched from generic timers. TierTap is built for casino loyalty reality.",
        "Property comparison in analytics helped me pick where to spend my time.",
        "Adding past sessions backfilled my history so charts weren’t empty on day one.",
        "The combo of timer, ledger, and loyalty goals is exactly what I wanted.",
        "Smooth close-out even when I’m tired at 2am. That matters more than it sounds.",
        "I trust the numbers because every buy-in and cash-out is explicit.",
        "Community is optional; core tracking works offline on device. Perfect balance.",
        "Tap Level progression makes consistent logging feel rewarding.",
        "Slot machine lists and game pickers are detailed enough for real floors.",
        "I recommend TierTap to every friend who cares about player’s cards.",
        "Best useful feature for me: seeing tier points earned per hour by property.",
        "Wallet photos of my cards plus live tier numbers—simple and powerful.",
        "Aborting a mistaken live session is easy; I’m not stuck with junk data.",
        "Uber and dining shortcuts after stopping the timer are a thoughtful end-of-night touch.",
        "History filters by game, location, and dates make deep dives fast.",
        "I use it every casino trip now. Became part of my routine like the player’s card.",
        "Clear win/loss alongside loyalty gain—finally both stories in one record.",
        "Program ladder picker removed the confusion around next-tier requirements.",
        "Live stack updates with a little celebration when I’m up feel polished.",
        "Most useful app in my casino toolkit. Logging + tiers + analytics in one place.",
        "I stopped guessing my year-to-date play. TierTap shows the truth.",
        "Fast check-in bar on Sessions is genius when I’m already at the table.",
        "Synced Watch and iPhone session state means I can start on one and finish on the other.",
        "Insightful without being preachy. It helps me see patterns and decide for myself.",
        "Beautiful charts, but the practical win is accurate session and tier logs.",
        "If you play for status or comps, this is the tracker that actually gets it.",
        "TierTap turned messy casino nights into clean, useful data I actually use.",
    ]

    /// Picks a random positive review comment for App Store pasteboard prefill.
    static func randomComment() -> String {
        all.randomElement() ?? all[0]
    }
}
