import Foundation

/// Generated openers and closers for 10,000+ phrase combinations per sentiment (tripled).
/// Combined with SessionShareFormatter's built-in phrases in SessionSharePhrases.
enum SessionSharePhrasesGenerated {

    static let positiveOpeners: [String] = [
        "You played with clarity and conviction from the first hand.",
        "You turned discipline into a visible edge tonight.",
        "You stayed ahead of the table flow the whole session.",
        "You made the table work for you instead of the other way around.",
        "You converted good position into consistent profit.",
        "You kept your range balanced and your opponents guessing.",
        "You showed real patience when the deck went quiet.",
        "You capitalized on every clear edge you found.",
        "You left money on the table only when it was the right fold.",
        "You blended aggression and caution in exactly the right mix.",
        "You read the table and adapted your strategy in real time.",
        "You stayed one step ahead of the action all night.",
        "You turned a solid plan into a solid result.",
        "You played with the confidence of someone who did the work.",
        "You made tough folds and got paid on the right calls.",
        "You kept your stack building without taking unnecessary risks.",
        "You showed up with a clear head and left with a clear win.",
        "You let your edge compound instead of forcing the action.",
        "You played each street with intention and awareness.",
        "You turned good cards into maximum value when it mattered.",
        "You stayed in control of the session from open to close.",
        "You made the kind of decisions that build long-term graphs.",
        "You respected the game and the game respected you back.",
        "You stayed present and it showed in every big pot.",
        "You ran well and played well – a rare and powerful combo.",
        "You kept your cool when the table got tricky.",
        "You extracted value without turning into a calling station.",
        "You picked the right moments to push and the right ones to fold.",
        "You played a session you can be proud to review.",
        "You turned theory into profit without overcomplicating things.",
        "You stayed within your system and your system delivered.",
        "You made the table pay for their mistakes without making your own.",
        "You closed out the session with your edge intact.",
        "You showed that steady pressure beats random aggression.",
        "You kept your mental stack as strong as your chip stack.",
        "You played like someone who's in it for the long run.",
        "You turned a good lineup into a great result.",
        "You stayed patient through the dry spells and got paid in the good ones.",
        "You made every chip count without playing scared.",
        "You left the table with more than just profit – with proof.",
        "You played a session that would hold up under review.",
        "You stayed true to your style and your style paid off.",
        "You turned a tough table into a profitable one.",
        "You kept your decision quality high from first hand to last.",
        "You showed that you can win without getting out of line.",
        "You made the most of every spot the game gave you.",
        "You played with the kind of focus that separates regs from recs.",
        "You stayed disciplined when it would have been easy to chase.",
        "You turned a winning session into a learning one too.",
        "You left with chips and with confidence for next time.",
        "You played the kind of session that builds a reputation.",
        "You applied your study at the table and it showed.",
        "You kept the initiative without overplaying your hands.",
        "You turned marginal spots into clear folds or clear value.",
        "You stayed level through the highs and the lulls.",
        "You made the river decisions that separate good from great.",
        "You played your stack size perfectly all night.",
        "You avoided the traps that caught others at the table.",
        "You built pots when you had it and got out when you didn't.",
        "You showed up ready and left with results to match.",
        "You kept your aggression purposeful, not reckless.",
        "You turned position into profit over and over.",
        "You stayed unreadable when it mattered most.",
        "You made the math work in your favor tonight.",
        "You played like someone who trusts their preparation.",
        "You kept the variance in perspective and kept executing.",
        "You turned a decent run into a strong session.",
        "You stayed committed to your plan from start to finish.",
        "You made the right move at the right time, repeatedly.",
        "You played with a calm that rubbed off on your decisions.",
        "You kept your bluffs rare and your value bets frequent.",
        "You turned good table selection into a great night.",
        "You stayed disciplined with your stop-loss and your take-profit.",
        "You made the tough calls and the tough folds when they counted.",
        "You played a session that reflects your best habits.",
        "You kept your emotions out of the big decisions.",
        "You turned a tricky lineup into a profitable one.",
        "You stayed focused on the process and the results followed.",
        "You made every hand count without forcing action.",
        "You played with the patience of someone who knows the math.",
        "You kept your range construction sharp all session.",
        "You turned a slow start into a strong finish.",
        "You stayed ahead of the curve when the table changed.",
        "You made the most of your image at the table.",
        "You played like a pro from the first orbit to the last.",
        "You kept your bet sizing consistent and effective.",
        "You turned reads into chips without overrelying on them.",
        "You stayed balanced between value and bluff lines.",
        "You made the session look easy even when it wasn't.",
        "You played with the kind of consistency that builds bankrolls.",
        "You kept your focus through the long stretches.",
        "You turned a good night into a great one.",
        "You stayed in the zone when the pots got big.",
        "You made the right adjustments as the game evolved.",
        "You played a session that would make any coach proud.",
        "You kept your cool in the spots that break most players.",
        "You turned solid play into a solid score.",
        "You stayed true to your edge and didn't chase.",
        "You made the kind of decisions that compound over time.",
        "You played with awareness of every player at the table.",
        "You kept your timing sharp on bluffs and value bets.",
        "You turned a tough spot into a learning moment and a win.",
        "You stayed committed to quality over quantity.",
        "You made the session count without letting it define you.",
        "You played like someone who's done the homework.",
        "You kept your stack moving in the right direction.",
        "You turned a break-even table into a winning one.",
        "You stayed resilient when a few hands went wrong.",
        "You made the river calls and folds that define sessions.",
        "You played with a clear head and a full heart.",
        "You kept your strategy flexible without losing your edge.",
        "You turned a standard session into an above-average result.",
        "You stayed in the moment and avoided tilt traps.",
        "You made the right play even when it was the hard play.",
        "You played a session that proves your edge is real.",
        "You kept your expectations in check and your execution high.",
        "You turned a good run into a session to remember.",
        "You stayed disciplined with your time and your chips.",
        "You made the table respect your raises and your folds.",
        "You played with the maturity the game demands.",
        "You kept your wins sustainable and your losses contained.",
        "You turned tonight into another brick in the foundation.",
        "You stayed sharp when others were slipping.",
        "You made the session a net positive in every way.",
        "You played like the best version of yourself tonight.",
        "You kept your edge visible without being predictable.",
        "You turned a challenging table into a profitable challenge.",
        "You stayed calm when the variance tried to rattle you.",
        "You made the right moves at the right times.",
        "You played a session that stacks with your long-term goals.",
        "You kept your aggression in the right places.",
        "You turned a winning night into a learning one too.",
        "You stayed ahead of tilt and ahead of the count.",
        "You made the session one you can look back on with pride.",
        "You brought your A-game and the results showed it.",
        "You kept your composure when the pots got big.",
        "You turned a tricky table into a profitable session.",
        "You played with the kind of patience that pays off.",
        "You made the right reads and acted on them.",
        "You stayed ahead of the variance curve tonight.",
        "You turned discipline into a clear edge at the table.",
        "You kept your focus locked in from first hand to last.",
        "You made every decision count without overthinking it.",
        "You played like someone who knows their edge.",
        "You stayed balanced when the table got aggressive.",
        "You turned good runouts into maximum value.",
        "You kept your stack growing without taking bad risks.",
        "You made the session look effortless from the outside.",
        "You played with a level head and a full stack.",
        "You stayed selective and got paid for it.",
        "You turned a tough lineup into a winning one.",
        "You kept your bluffs credible and your value thin.",
        "You made the kind of folds that save sessions.",
        "You played with intention on every street.",
        "You stayed in the zone when it mattered most.",
        "You turned a break-even night into a winning one.",
        "You kept your bet sizing in the sweet spot.",
        "You made the table adapt to you, not the other way around.",
        "You played a session that reflects your best work.",
        "You stayed calm through the inevitable coolers.",
        "You turned position into profit all night long.",
        "You kept your range uncapped when it mattered.",
        "You made the right moves at the right times, again and again.",
        "You played with the confidence of a seasoned reg.",
        "You stayed one step ahead of the table flow.",
        "You turned a slow grind into a solid score.",
        "You kept your emotions in check when the stakes rose.",
        "You made the river decisions that define winning sessions.",
        "You played like someone who's done the work.",
        "You stayed disciplined with your time at the table.",
        "You turned a good table into a great result.",
        "You kept your aggression in check when it wasn't warranted.",
        "You made the session a net positive for your bankroll and your mindset.",
        "You played with the kind of clarity that wins long term.",
        "You stayed true to your strategy when others were tilting.",
        "You turned a marginal spot into a clear fold or a clear value bet.",
        "You kept your image strong and used it when it counted.",
        "You made the most of a table that was willing to pay you off.",
        "You played a session you'd be happy to review on camera.",
        "You stayed patient when the deck went cold.",
        "You turned a decent run into a session to remember.",
        "You kept your mental game as sharp as your technical game.",
        "You made the right call in the spots that defined the night.",
        "You played with the kind of consistency that builds graphs.",
        "You stayed ahead of the curve when the dynamics shifted.",
        "You turned a tough spot into a learning moment and a win.",
        "You kept your stack moving in the right direction all night.",
        "You made the session count without forcing the action.",
        "You played like the best version of yourself from start to finish.",
        "You stayed focused on execution, not on outcomes.",
        "You turned a good night into a great one with discipline.",
        "You kept your ranges balanced and your opponents off balance.",
        "You made the kind of laydowns that separate good from great.",
        "You played with awareness of every player and every pot.",
        "You stayed in control when the variance tried to bite.",
        "You turned a challenging session into a profitable one.",
        "You kept your edge visible without being exploitable.",
        "You made the table pay for their mistakes time and again.",
        "You played a session that would make any mentor proud.",
        "You stayed resilient when a few hands went the wrong way.",
        "You turned solid fundamentals into a solid result.",
        "You kept your timing sharp on both value and bluff lines.",
        "You made the right play even when it was the unpopular one.",
        "You played with the maturity that the game rewards.",
        "You stayed committed to your plan when the table got tough.",
        "You turned a standard night into an above-average score.",
        "You kept your cool in the spots that break most players.",
        "You made the session one you can point to with pride.",
        "You played like someone who trusts the process.",
        "You stayed ahead of tilt and ahead of the count all night.",
        "You turned a break-even table into a winning session.",
        "You kept your strategy flexible when the game demanded it.",
        "You made the river calls and folds that build bankrolls.",
        "You played with a clear plan and executed it well.",
        "You stayed disciplined when the table got splashy.",
        "You turned a good run into a session that compounds.",
        "You kept your aggression purposeful and your folds disciplined.",
        "You made the most of every opportunity the game gave you.",
        "You played a session that stacks with your long-term edge.",
        "You stayed present and avoided the tilt traps.",
        "You turned a tough table into a profitable grind.",
        "You kept your bet sizing consistent and effective all night.",
        "You made the session a testament to your preparation.",
        "You played with the kind of focus that wins in the long run.",
        "You stayed in the zone when the pots got big.",
        "You turned a decent lineup into a great result.",
        "You kept your reads sharp and your execution sharper.",
        "You made the right adjustments as the night went on.",
        "You played like someone who can close out a good session.",
        "You stayed true to your edge and didn't chase.",
        "You turned a slow start into a strong finish with patience.",
        "You kept your stack building without overextending.",
        "You made the session one you can build on next time.",
        "You played with the confidence that comes from preparation.",
        "You stayed level through the highs and the lulls.",
        "You turned a good spot into a great one with the right bet.",
        "You kept your range construction sharp from open to close.",
        "You made the table work for every chip they won from you.",
        "You played a session that reflects your growth.",
        "You stayed composed when the variance swung the wrong way.",
        "You turned a tricky lineup into a winning night.",
        "You kept your mental stack as strong as your chip stack all session.",
        "You made the kind of decisions that compound over time.",
        "You played with awareness of position and stack sizes.",
        "You stayed disciplined with your buy-in and your cash-out.",
        "You turned a marginal table into a profitable one.",
        "You kept your bluffs few and your value bets many.",
        "You made the session a net positive in every way that matters.",
        "You played like someone who's in it for the long run.",
        "You stayed focused on quality over quantity all night.",
        "You turned a tough run into a session you can be proud of.",
        "You kept your aggression in the right spots.",
        "You made the right move at the right time, over and over.",
        "You played with the kind of patience that the game rewards.",
        "You stayed ahead of the action when it mattered.",
        "You turned a good table into a great session with discipline.",
        "You kept your emotions out of the big decisions.",
        "You made the session one you can reference for future tough spots.",
        "You played a session that proves your edge is real.",
        "You stayed in control of the pace and the pressure.",
        "You turned a challenging night into a winning one.",
        "You kept your strategy simple and your execution sharp.",
        "You made the most of your edge when the table gave you spots.",
        "You played with the clarity that comes from good habits.",
        "You stayed resilient when a few pots went the wrong way.",
        "You turned a standard session into an above-average result.",
        "You kept your cool when the table got aggressive.",
        "You made the session count for your bankroll and your confidence.",
        "You played like someone who knows how to win.",
        "You stayed disciplined when it would have been easy to chase.",
        "You turned a break-even run into a winning session.",
        "You kept your focus through the long stretches.",
        "You made the right folds and the right calls when they counted.",
        "You played with the kind of consistency that builds careers.",
        "You stayed true to your style and got paid for it.",
        "You turned a good night into a great one with smart play.",
        "You kept your range balanced and your opponents guessing all night.",
        "You made the session one you can look back on with pride.",
        "You played a session that would hold up under review.",
        "You stayed ahead of the curve when the table changed.",
        "You turned a tough lineup into a profitable one.",
        "You kept your bet sizing in the right range all session.",
        "You made the table respect your raises and your checks.",
        "You played with the maturity that separates regs from recs.",
        "You stayed in the moment and avoided the tilt traps.",
        "You turned a decent session into a strong one with discipline.",
        "You kept your aggression measured and your folds disciplined.",
        "You made the kind of decisions that build long-term graphs.",
        "You played like someone who's done the homework.",
        "You stayed composed through the inevitable swings.",
        "You turned a good run into a session to remember.",
        "You kept your stack moving in the right direction.",
        "You made the session a building block for something bigger.",
        "You played with the kind of focus that wins sessions.",
        "You stayed patient when the deck went quiet.",
        "You turned a challenging table into a winning one.",
        "You kept your reads sharp and your execution sharper all night.",
        "You made the right play in the spots that defined the session.",
        "You played a session that reflects your best habits.",
        "You stayed disciplined with your time and your chips.",
        "You turned a slow grind into a solid score with patience.",
        "You kept your edge visible without being predictable.",
        "You made the session one you can build on.",
        "You played with the confidence of someone who belongs.",
        "You stayed ahead of the action all night long.",
        "You turned a marginal night into a profitable one.",
        "You kept your mental game as strong as your technical game.",
        "You made the most of every spot the game gave you.",
        "You played like the best version of yourself tonight.",
        "You stayed in control when the variance swung.",
        "You turned a good lineup into a great result.",
        "You kept your strategy flexible without losing your edge.",
        "You made the session a net positive for your graph.",
        "You played with the kind of patience that pays off.",
        "You stayed focused on the process and the results followed.",
        "You turned a tough spot into a learning moment and a win.",
        "You kept your aggression in the right places all session.",
        "You made the right calls and the right folds when they mattered.",
        "You played a session that stacks with your goals.",
        "You stayed true to your edge and didn't overplay.",
        "You turned a decent night into a winning session.",
        "You kept your composure when the pots got big.",
        "You made the session one you can point to with pride.",
        "You played with the clarity that comes from good preparation.",
        "You stayed level through the highs and the lulls of the session.",
        "You turned a break-even table into a profitable one.",
        "You kept your timing sharp on value and bluff lines.",
        "You made the kind of folds that save money and sessions.",
        "You played like someone who can handle the variance.",
        "You stayed disciplined when the table got loose.",
        "You turned a good table into a great night with smart play.",
        "You kept your stack building without taking bad risks.",
        "You made the session count without forcing the action.",
        "You played with the kind of consistency that builds bankrolls.",
        "You stayed ahead of the table flow the whole way.",
        "You turned a tricky night into a profitable one.",
        "You kept your emotions out of the big pots.",
        "You made the right moves at the right times tonight.",
        "You played a session that would make any coach proud.",
        "You stayed in the zone when the stakes rose.",
        "You turned a standard night into an above-average result.",
        "You kept your range uncapped when it mattered most.",
        "You made the session a testament to your discipline.",
        "You played with the maturity the game demands.",
        "You stayed resilient when a few hands went wrong.",
        "You turned a challenging session into a winning one.",
        "You kept your focus locked in from first hand to last.",
        "You made the most of your edge when the spots came.",
        "You played like someone who trusts their reads.",
        "You stayed composed and it showed in every big pot.",
        "You turned a good run into a session to remember.",
        "You kept your aggression purposeful, not reckless.",
        "You made the session one you can reference for the future.",
        "You played with the kind of focus that separates good from great.",
        "You stayed true to your plan when the table got tough.",
        "You turned a marginal session into a profitable one.",
        "You kept your bet sizing in the sweet spot all night.",
        "You made the table adapt to you tonight.",
        "You played a session that reflects your growth as a player.",
        "You stayed ahead of tilt and ahead of the count.",
        "You turned a slow start into a strong finish.",
        "You kept your mental stack as strong as your chip stack.",
        "You made the right play even when it was the hard one.",
        "You played like the best version of yourself from open to close.",
        "You stayed disciplined with your stop-loss and take-profit.",
        "You turned a decent session into a strong one.",
        "You kept your reads sharp and your execution sharp.",
        "You made the session a building block for your graph.",
        "You played with the confidence that comes from doing the work.",
        "You stayed in control of the session from start to finish.",
        "You turned a tough table into a profitable session.",
        "You kept your strategy simple and effective.",
        "You made the kind of decisions that compound.",
        "You played a session that proves you belong at the table.",
        "You stayed patient and let the game come to you.",
        "You turned a good night into a great one.",
        "You kept your edge intact from first hand to last.",
        "You made the session one you can look back on with pride.",
        "You stayed disciplined when the table got splashy.",
        "You turned a marginal run into a profitable session.",
        "You kept your aggression in check when it wasn't warranted.",
        "You made the session a net positive for your graph.",
        "You played with the kind of clarity that wins long term.",
        "You stayed true to your strategy when others were tilting.",
        "You turned a decent run into a strong session.",
        "You kept your image strong and used it when it counted.",
        "You made the most of a table that was willing to pay you off.",
        "You played a session you'd be happy to review on camera.",
        "You stayed patient when the deck went cold.",
        "You turned a good run into a session to remember.",
        "You kept your mental game as sharp as your technical game.",
        "You made the right call in the spots that defined the night.",
        "You played with the kind of consistency that builds graphs.",
        "You stayed ahead of the curve when the dynamics shifted.",
        "You turned a tough spot into a learning moment and a win.",
        "You kept your stack moving in the right direction all night.",
        "You made the session count without forcing the action.",
        "You played like the best version of yourself from start to finish.",
        "You stayed focused on execution, not on outcomes.",
        "You turned a good night into a great one with discipline.",
        "You kept your ranges balanced and your opponents off balance.",
        "You made the kind of laydowns that separate good from great.",
        "You played with awareness of every player and every pot.",
        "You stayed in control when the variance tried to bite.",
        "You turned a challenging session into a profitable one.",
        "You kept your edge visible without being exploitable.",
        "You made the table pay for their mistakes time and again.",
        "You played a session that would make any mentor proud.",
        "You stayed resilient when a few hands went the wrong way.",
        "You turned solid fundamentals into a solid result.",
        "You kept your timing sharp on both value and bluff lines.",
        "You made the right play even when it was the unpopular one.",
        "You played with the maturity that the game rewards.",
        "You stayed committed to your plan when the table got tough.",
        "You turned a standard night into an above-average score.",
        "You kept your cool in the spots that break most players.",
        "You made the session one you can point to with pride.",
        "You played like someone who trusts the process.",
        "You stayed ahead of tilt and ahead of the count all night.",
        "You turned a break-even table into a winning session.",
        "You kept your strategy flexible when the game demanded it.",
        "You made the river calls and folds that build bankrolls.",
        "You played with a clear plan and executed it well.",
        "You stayed disciplined when the table got splashy.",
        "You turned a good run into a session that compounds.",
        "You kept your aggression purposeful and your folds disciplined.",
        "You made the most of every opportunity the game gave you.",
        "You played a session that stacks with your long-term edge.",
        "You stayed present and avoided the tilt traps.",
        "You turned a tough table into a profitable grind.",
        "You kept your bet sizing consistent and effective all night.",
        "You made the session a testament to your preparation.",
        "You played with the kind of focus that wins in the long run.",
        "You stayed in the zone when the pots got big.",
        "You turned a decent lineup into a great result.",
        "You kept your reads sharp and your execution sharper.",
        "You made the right adjustments as the night went on.",
    ]

    static let positiveClosers: [String] = [
        "Keep building sessions like this and the graph will speak for itself.",
        "This is the kind of night that makes the grind worth it.",
        "Let this session be a template for the next hundred.",
        "You're proving that discipline and skill beat luck over time.",
        "Keep turning good process into good results.",
        "This win is a down payment on your long-term edge.",
        "Let this be evidence that your approach works in the wild.",
        "You're stacking the kind of sessions that build careers.",
        "Keep showing up with this level of intention.",
        "This session belongs in the 'repeat this' column.",
        "Let this reinforce that you can win without running hot.",
        "You're building a sample size you can be proud of.",
        "Keep trusting the work you put in before the session.",
        "This is what it looks like when preparation meets opportunity.",
        "Let this be one of many nights where your edge showed up.",
        "You're turning potential into results, one session at a time.",
        "Keep protecting your edge the way you did tonight.",
        "This kind of session is how bankrolls and confidence grow.",
        "Let this sit in your memory for the next tough night.",
        "You're playing a game that can last a lifetime.",
        "Keep making the boring, correct plays that add up.",
        "This session is a vote of confidence in your system.",
        "Let this be proof that you can close out a good night.",
        "You're building habits that will outlast any downswing.",
        "Keep treating each hand with the respect you showed here.",
        "This is the standard you've been working toward.",
        "Let this win be a quiet reminder that you belong.",
        "You're creating a track record that speaks for itself.",
        "Keep bringing this version of yourself to the table.",
        "This session shows that your best game is accessible.",
        "Let this be a stepping stone, not a peak.",
        "You're learning to win without needing to get lucky.",
        "Keep stacking small edges into big results.",
        "This is how sustainable poker looks in practice.",
        "Let this be one more data point in a winning trend.",
        "You're proving that you can execute under real conditions.",
        "Keep your process clean and your results will follow.",
        "This session is a gift to your future self.",
        "Let this reinforce your commitment to good habits.",
        "You're building the kind of confidence that doesn't tilt.",
        "Keep making decisions you can defend in review.",
        "This win is a product of skill, not a fluke.",
        "Let this be a reminder that you're capable of this anytime.",
        "You're turning theory into consistent execution.",
        "Keep protecting your mental game like you did tonight.",
        "This session is exactly what your bankroll needed.",
        "Let this be fuel for the next session, not complacency.",
        "You're showing that you can play for the long run.",
        "Keep stacking nights like this and the variance will smooth.",
        "This is the kind of result that comes from patience.",
        "Let this be a baseline you can return to.",
        "You're building a style that works under pressure.",
        "Keep trusting your reads when they're this sharp.",
        "This session deserves a place in your highlight reel.",
        "Let this be one of many professional-quality nights.",
        "You're proving that you can win without forcing.",
        "Keep your standards right where they were tonight.",
        "This win is a reflection of your preparation.",
        "Let this session remind you what you're capable of.",
        "You're creating a graph that tells a winning story.",
        "Keep making the kind of folds and raises you made here.",
        "This is what happens when focus meets opportunity.",
        "Let this be a quiet confidence boost for the road.",
        "You're building the resilience that long-term play requires.",
        "Keep approaching each session with this level of care.",
        "This session is a testament to your growth.",
        "Let this be evidence that your edge is real and repeatable.",
        "You're turning good habits into good results.",
        "Keep stacking sessions that you can be proud of.",
        "This is the kind of night that builds lasting confidence.",
        "Let this be a reminder that discipline pays off.",
        "You're playing a game that rewards the approach you took.",
        "Keep making the high-quality decisions you made tonight.",
        "This session is a building block for something bigger.",
        "Let this be one of many nights where you showed up.",
        "You're proving that you can win with consistency.",
        "Keep your head in the same place it was tonight.",
        "This win is a product of the work you've put in.",
        "Let this session sit alongside your best memories.",
        "You're building a body of work that proves your edge.",
        "Keep trusting your process when it delivers like this.",
        "This is exactly the kind of session to build on.",
        "Let this be a reference point for future tough decisions.",
        "You're turning effort into results in a sustainable way.",
        "Keep showing up with this level of clarity.",
        "This session is a vote for your long-term approach.",
        "Let this be proof that you can execute when it matters.",
        "You're building the kind of track record that matters.",
        "Keep making the disciplined plays that won tonight.",
        "This is what it looks like when everything clicks.",
        "Let this be a reminder that you're on the right path.",
        "You're creating sessions that compound over time.",
        "Keep your expectations grounded and your execution high.",
        "This session is a gift to your future graph.",
        "Let this be one more reason to trust your preparation.",
        "You're proving that you can win without heroics.",
        "Keep stacking the kind of nights that build bankrolls.",
        "This is the standard you're capable of every time.",
        "Let this be a quiet celebration of good process.",
        "You're building a game that travels to any table.",
        "Keep making the kind of decisions you made tonight.",
        "This session is a down payment on your goals.",
        "Let this reinforce that you're building something real.",
        "You're turning discipline into a competitive advantage.",
        "Keep showing up with this level of focus.",
        "This win is a reflection of your commitment.",
        "Let this be a template for the next session.",
        "You're building the kind of confidence that lasts.",
        "Keep trusting your edge when it shows up like this.",
        "This session is exactly what you've been working for.",
        "Let this be one of many nights where you executed.",
        "You're proving that you can win with patience.",
        "Keep your process as clean as it was tonight.",
        "This is the kind of result that compounds.",
        "Let this be a reminder that your best game is in you.",
        "You're creating a track record of quality play.",
        "Keep making the thoughtful decisions you made here.",
        "This session is a testament to your approach.",
        "Let this be evidence that you're ready for this level.",
        "You're turning preparation into profit, again.",
        "Keep stacking sessions that hold up under review.",
        "This is what sustainable winning looks like.",
        "Let this be a quiet nod to the work you've put in.",
        "You're building something that can last a lifetime.",
        "Keep bringing the same intention to the next session.",
        "This win is a product of skill and patience.",
        "Let this session be a cornerstone of your confidence.",
        "You're proving that you can close out a good night.",
        "Keep your standards where they were tonight.",
        "This is the kind of night that makes the grind worth it.",
        "Let this be one more brick in a solid foundation.",
        "You're turning good process into consistent results.",
        "Keep making the kind of plays that won tonight.",
        "This session is a reminder that you belong.",
        "Let this be fuel for the next tough session.",
        "You're building a graph that rewards patience.",
        "Keep trusting your reads and your preparation.",
        "This is exactly the kind of session to repeat.",
        "Let this be a reference for what good looks like.",
        "You're creating sessions that you can be proud of.",
        "Keep stacking sessions like this and the graph will reward you.",
        "This is the kind of execution that builds lasting edges.",
        "Let this be one of many nights where your edge showed up.",
        "You're proving that you can win with discipline and skill.",
        "Keep making the kind of decisions you made tonight.",
        "This session is a reminder that your process works.",
        "Let this reinforce that you belong at this level.",
        "You're building a graph that rewards patience and execution.",
        "Keep your standards right where they were tonight.",
        "This win is a product of your preparation and your poise.",
        "Let this be a template for future sessions.",
        "You're turning good habits into consistent results.",
        "Keep trusting your edge when it shows up like this.",
        "This is exactly the kind of session to repeat.",
        "Let this be proof that you can close out a good night.",
        "You're building the kind of track record that compounds.",
        "Keep showing up with this level of focus and intention.",
        "This session belongs in the 'repeat this' column.",
        "Let this be a reminder that your best game is in you.",
        "You're creating a body of work that proves your edge.",
        "Keep making the boring, profitable plays that add up.",
        "This is what it looks like when discipline meets opportunity.",
        "Let this be one more brick in a solid foundation.",
        "You're proving that you can win without running hot.",
        "Keep protecting your mental game the way you did here.",
        "This session is a gift to your future self.",
        "Let this be evidence that your approach works live.",
        "You're building habits that will outlast any downswing.",
        "Keep stacking nights like this and the variance will smooth.",
        "This is the kind of result that comes from good process.",
        "Let this be a baseline you can return to.",
        "You're turning preparation into profit, again.",
        "Keep bringing this version of yourself to the table.",
        "This win is a reflection of your commitment and your skill.",
        "Let this session sit alongside your best memories.",
        "You're building a style that works under pressure.",
        "Keep making the high-quality decisions you made tonight.",
        "This is exactly the kind of session to build on.",
        "Let this be a reference point for future tough spots.",
        "You're proving that you can execute when it matters.",
        "Keep your process as clean as it was tonight.",
        "This session is a testament to your growth and your edge.",
        "Let this be fuel for the next session, not complacency.",
        "You're creating sessions that compound over time.",
        "Keep trusting your reads and your preparation.",
        "This is the standard you're capable of every time.",
        "Let this be a quiet reminder that you belong.",
        "You're building something that can last a lifetime.",
        "Keep making the kind of folds and raises you made here.",
        "This session is a down payment on your long-term goals.",
        "Let this reinforce your commitment to good habits.",
        "You're turning good process into consistent results.",
        "Keep stacking sessions that hold up under review.",
        "This is what sustainable winning looks like in practice.",
        "Let this be one more reason to trust your preparation.",
        "You're proving that you can win with patience and skill.",
        "Keep your expectations grounded and your execution high.",
        "This session is a reminder that your edge is real.",
        "Let this be a cornerstone of your confidence.",
        "You're building a game that travels to any table.",
        "Keep making the thoughtful decisions you made here.",
        "This is the kind of night that makes the grind worth it.",
        "Let this be proof that you can execute under pressure.",
        "You're creating a track record that speaks for itself.",
        "Keep showing up with this level of clarity and focus.",
        "This win is a product of skill, patience, and preparation.",
        "Let this be a stepping stone, not a peak.",
        "You're building the kind of confidence that doesn't tilt.",
        "Keep protecting your edge the way you did tonight.",
        "This session is exactly what your bankroll and mindset needed.",
        "Let this be one of many professional-feeling sessions.",
        "You're turning theory into consistent execution.",
        "Keep stacking the kind of nights that build bankrolls.",
        "This is the kind of result that compounds over time.",
        "Let this be a reminder that you're on the right path.",
        "You're proving that you can close out a good session.",
        "Keep making the disciplined plays that won tonight.",
        "This session is a building block for something bigger.",
        "Let this be evidence that you're ready for this level.",
        "You're building the resilience that long-term play requires.",
        "Keep trusting your process when it delivers like this.",
        "This is what happens when focus meets opportunity.",
        "Let this be a quiet celebration of good process.",
        "You're creating sessions that you can be proud of.",
        "Keep approaching each session with this level of care.",
        "This session is a vote of confidence in your system.",
        "Let this be a reminder that discipline pays off.",
        "You're turning effort into results in a sustainable way.",
        "Keep your head in the same place it was tonight.",
        "This is the kind of session that builds lasting confidence.",
        "Let this be a template for the next hundred sessions.",
        "You're building a body of work that proves your edge.",
        "Keep making the kind of plays that won tonight.",
        "This session is a reminder that you belong.",
        "Let this be fuel for the next tough session.",
        "You're proving that you can win with consistency.",
        "Keep stacking sessions that you can be proud of.",
        "This is exactly the kind of session to repeat.",
        "Let this be a reference for what good looks like.",
        "You're building a graph that tells a winning story.",
        "Keep bringing the same intention to the next session.",
        "This win is a reflection of your preparation and your poise.",
        "Let this session be a cornerstone of your confidence.",
        "You're creating a track record of quality play.",
        "Keep making the kind of decisions you made tonight.",
        "This is what it looks like when everything clicks.",
        "Let this be a reminder that your edge is real and repeatable.",
        "You're building the kind of track record that matters.",
        "Keep trusting your edge when it shows up like this.",
        "This session is a testament to your approach.",
        "Let this be one more data point in a winning trend.",
        "You're turning discipline into a competitive advantage.",
        "Keep your standards where they were tonight.",
        "This is the kind of night that builds lasting confidence.",
        "Let this be proof that you can win without heroics.",
        "You're building something durable with sessions like this.",
        "Keep making the kind of folds and raises you made here.",
        "This session is a gift to your future graph.",
        "Let this reinforce that you're building something real.",
        "You're proving that you can execute when it matters.",
        "Keep stacking nights like this and the long run takes care of itself.",
        "This is the standard you've been working toward.",
        "Let this be one of many nights where you showed up.",
        "You're creating sessions that compound over time.",
        "Keep protecting your mental game like you did tonight.",
        "This session is a reminder that you can beat this environment.",
        "Let this be a baseline, not a high point.",
        "You're building a game that wears well over time.",
    ]

    static let negativeOpeners: [String] = [
        "The deck had other plans tonight.",
        "Variance showed up in a big way this session.",
        "This one will go in the 'character building' file.",
        "The runouts were not in your corner tonight.",
        "You got a heavy dose of the downside this time.",
        "The session refused to give you much to work with.",
        "You were on the wrong end of too many key pots.",
        "The cards never really got out of first gear for you.",
        "This session tested your patience more than your skill.",
        "You ran into a string of brutal runouts.",
        "The table was a tough place to find an edge tonight.",
        "You had to swallow some hard results this time.",
        "The variance train made a long stop at your seat.",
        "You saw more chips leave your stack than stay.",
        "The session leaned hard into the unforgiving side of the game.",
        "You got a reminder that poker doesn't care about fairness.",
        "The river was unkind more often than not tonight.",
        "You had to grind through a lot of small losses.",
        "This one felt like the deck was working against you.",
        "You ran into the kind of session that humbles everyone.",
        "The pots that mattered kept slipping the wrong way.",
        "You had to make peace with a negative number tonight.",
        "The session gave you more lessons than wins.",
        "You got squeezed in too many marginal spots.",
        "The lineup had your number more often than you had theirs.",
        "You had to absorb a lot of variance in one sitting.",
        "This session was long on frustration and short on momentum.",
        "You ran below expectation in way too many hands.",
        "The board kept pairing your opponents and not you.",
        "You had to fold more winners than you'd like to admit.",
        "The session never really gave you a chance to breathe.",
        "You got a full serving of negative variance tonight.",
        "The key hands kept landing on the wrong side of the line.",
        "You had to sit through a lot of tough beats.",
        "This one was heavy on the kind of spots you want to forget.",
        "You ran into coolers and bad timing in equal measure.",
        "The table was a tough place to find a rhythm.",
        "You had to weather a session that didn't want to cooperate.",
        "The runouts seemed to favor everyone else tonight.",
        "You got a taste of the downside that comes with the game.",
        "The session asked for more than it gave back.",
        "You had to make a lot of tough folds that still hurt.",
        "This session was a reminder that variance is real.",
        "You ran into the kind of night that tests your resolve.",
        "The deck was cold when you had heat and hot when you didn't.",
        "You had to watch your stack shrink more than grow.",
        "The session leaned into the painful side of variance.",
        "You got put in too many no-win situations tonight.",
        "The pots you needed to win kept getting away.",
        "You had to absorb a lot of small edges going the wrong way.",
        "This one was a masterclass in negative variance.",
        "You ran into a table that didn't give much back.",
        "The river was a villain tonight, not a friend.",
        "You had to sit through a lot of second-best hands.",
        "The session was stingy with its rewards.",
        "You got a full dose of the variance that makes poker hard.",
        "The key spots kept breaking the wrong way.",
        "You had to make peace with a losing session.",
        "This session was long on pain and short on payoff.",
        "You ran into the kind of runouts that make you sigh.",
        "The table had your timing off all night.",
        "You had to fold more strong hands than you'd like.",
        "The session gave you more bruises than wins.",
        "You got a reminder that not every night can be a winner.",
        "The board kept telling you stories you didn't want to hear.",
        "You had to weather a lot of chips going the wrong direction.",
        "This one was heavy on the tuition side of the game.",
        "You ran into variance in its least friendly form.",
        "The deck was in a punishing mood tonight.",
        "You had to absorb more losses than wins.",
        "The session never really let you get ahead.",
        "You got a taste of the downswing that every player knows.",
        "The key runouts kept landing in the wrong column.",
        "You had to sit through a session that didn't cooperate.",
        "This session was a tough way to spend a night.",
        "You ran into the kind of variance that doesn't feel fair.",
        "The table was a hard place to find traction tonight.",
        "You had to make a lot of good folds that still cost you.",
        "The session leaned hard into the losing side.",
        "You got a full serving of the game's tougher moments.",
        "The pots that could have turned the night kept slipping away.",
        "You had to watch a lot of good situations go bad.",
        "This one was heavy on the kind of variance that stings.",
        "You ran into a lineup that didn't give you much.",
        "The river kept rewriting your hand in the wrong direction.",
        "You had to absorb a session that didn't want to give.",
        "The session was a reminder that downswings are part of the deal.",
        "You got put in too many spots where the math didn't help.",
        "The key hands kept ending in the wrong stack.",
        "You had to make peace with a night that didn't go your way.",
        "This session was long on lessons and short on profit.",
        "You ran into the kind of night that tests your mental game.",
        "The deck was not in a generous mood tonight.",
        "You had to fold a lot of hands that looked good until the river.",
        "The session gave you more pain than momentum.",
        "You got a concentrated dose of negative variance.",
        "The table was tough and the runouts were tougher.",
        "You had to sit through a lot of chips moving the wrong way.",
        "This one was a full tour of the downside of variance.",
        "You ran into runouts that didn't respect your equity.",
        "The session never gave you the break you needed.",
        "You had to weather a night that leaned the wrong way.",
        "The key spots kept going to the other side of the table.",
        "You got a reminder that variance doesn't care about your plan.",
        "The board was unkind in too many big pots tonight.",
        "You had to absorb a lot of the game's harder moments.",
        "This session was heavy on the kind of results that hurt.",
        "You ran into a table that had your number.",
        "The deck was cold when it mattered most tonight.",
        "You had to make a lot of tough decisions that didn't pay off.",
        "The session gave you more setbacks than opportunities.",
        "You got a taste of the kind of night that builds character.",
        "The pots you needed kept ending in the wrong hands.",
        "You had to sit through variance in its rawest form.",
        "This one was a reminder that not every session can be a win.",
        "You ran into the kind of runouts that make you question things.",
        "The table was a hard place to find an edge tonight.",
        "You had to fold more than you'd like and lose more than you wanted.",
        "The session leaned into the painful side of the curve.",
        "You got a full dose of the variance that makes the game hard.",
        "The key runouts kept favoring the other side tonight.",
        "You had to make peace with a session that didn't cooperate.",
        "This session was long on variance and short on justice.",
        "You ran into the kind of night that every player dreads.",
        "The deck was in a punishing mood when you had chips in.",
        "You had to watch a lot of good equity turn into bad results.",
        "The session gave you more red numbers than green.",
        "You got a reminder that downswings are part of the journey.",
        "The board kept pairing the wrong hands tonight.",
        "You had to absorb a lot of the game's tougher variance.",
        "This one was heavy on the tuition side of poker.",
        "You ran into a session that didn't want to give you much.",
        "The table was stingy with its rewards tonight.",
        "You had to sit through a lot of runouts that didn't go your way.",
        "The session was a full serving of negative variance.",
        "You got put in too many spots where the deck said no.",
        "The key hands kept landing in the wrong column.",
        "You had to make peace with a night that tested your resolve.",
        "This session was a tough reminder that variance is real.",
        "You ran into the kind of runouts that make the game humbling.",
        "The deck was not your friend tonight.",
        "You had to weather a session that gave more than it took – the wrong way.",
        "The session gave you more pain than profit.",
        "You got a taste of the downside that comes with playing for real.",
        "The deck was cold when you had chips in the middle.",
        "You ran into more than your share of bad runouts tonight.",
        "The session was a reminder that variance can be brutal.",
        "You had to fold a lot of hands that looked good on the flop.",
        "The table was a tough place to find a rhythm.",
        "You got a full tour of the downside of the variance curve.",
        "The key pots kept ending up in the wrong stack.",
        "You had to absorb a lot of chips going the wrong way.",
        "This session was heavy on the kind of variance that stings.",
        "The runouts didn't respect your equity tonight.",
        "You ran into a night that tested your emotional bankroll.",
        "The board kept telling you no when you needed yes.",
        "You had to sit through a lot of second-best hands.",
        "The session gave you more setbacks than opportunities.",
        "You got a reminder that downswings are part of the game.",
        "The pots you needed to win kept slipping away.",
        "You had to make peace with a lot of losing flips.",
        "This one was a masterclass in negative variance.",
        "The deck was in a punishing mood tonight.",
        "You ran into runouts that didn't go your way.",
        "The table had your number more often than not.",
        "You had to weather a session that didn't want to give.",
        "The session was long on pain and short on payoff.",
        "You got a concentrated dose of the game's tougher side.",
        "The key hands kept breaking the wrong way.",
        "You had to watch your stack shrink more than grow.",
        "This session was a tough way to spend a night.",
        "The variance train made a long stop at your seat tonight.",
        "You ran into the kind of runouts that make you sigh.",
        "The river was unkind in too many big pots.",
        "You had to absorb more losses than wins.",
        "The session never really let you get comfortable.",
        "You got put in too many spots where the deck said no.",
        "The key runouts kept landing in the wrong column.",
        "You had to sit through variance in its rawest form.",
        "This one was heavy on the tuition side of the game.",
        "The deck was not in a generous mood tonight.",
        "You ran into a lineup that didn't give much back.",
        "The session gave you more red numbers than green.",
        "You had to make a lot of good folds that still cost you.",
        "The pots that mattered kept going the wrong way.",
        "You got a full serving of negative variance.",
        "The table was stingy with its rewards tonight.",
        "You had to fold more strong hands than you'd like.",
        "This session was a reminder that not every night can be a winner.",
        "The board kept pairing the wrong hands tonight.",
        "You ran into the kind of night that tests your resolve.",
        "The session leaned hard into the losing side.",
        "You had to watch a lot of good equity turn into bad results.",
        "The key spots kept favoring the other side of the table.",
        "You got a taste of the downswing that every player knows.",
        "The deck was cold when it mattered most tonight.",
        "You had to absorb a lot of the game's harder moments.",
        "This session was long on variance and short on justice.",
        "The runouts seemed to favor everyone else tonight.",
        "You ran into a session that didn't want to cooperate.",
        "The session gave you more bruises than wins.",
        "You had to make peace with a negative number tonight.",
        "The key hands kept ending in the wrong stack.",
        "You got a reminder that variance doesn't care about your plan.",
        "The table was a hard place to find an edge tonight.",
        "You had to sit through a lot of runouts that didn't go your way.",
        "This one was a full tour of the downside of variance.",
        "The deck was in a punishing mood when you had chips in.",
        "You ran into the kind of session that humbles everyone.",
        "The session never gave you the break you needed.",
        "You had to weather a night that leaned the wrong way.",
        "The pots you needed kept ending in the wrong hands.",
        "You got a concentrated dose of negative variance.",
        "The board was unkind in too many big pots tonight.",
        "You had to absorb a lot of chips going the wrong direction.",
        "This session was heavy on the kind of results that hurt.",
        "The variance showed up in a big way tonight.",
        "You ran into a table that had your number.",
        "The session gave you more pain than momentum.",
        "You had to make a lot of tough decisions that didn't pay off.",
        "The key runouts kept favoring the other side tonight.",
        "You got a reminder that downswings are part of the journey.",
        "The deck was not your friend tonight.",
        "You had to sit through more setbacks than successes.",
        "This one was a reminder that variance is real.",
        "The table was tough and the runouts were tougher.",
        "You ran into runouts that didn't respect your equity.",
        "The session gave you more lessons than wins.",
        "You had to fold more than you'd like and lose more than you wanted.",
        "The key pots kept slipping the wrong way.",
        "You got a full dose of the variance that makes the game hard.",
        "The board kept rewriting your hand in the wrong direction.",
        "You had to absorb a session that didn't want to give.",
        "This session was a tough reminder that variance is real.",
        "The deck was cold when you had heat and hot when you didn't.",
        "You ran into the kind of night that every player dreads.",
        "The session leaned into the painful side of the curve.",
        "You had to watch a lot of small losses stack into something bigger.",
        "The key hands kept landing in the wrong column.",
        "You got a taste of the kind of night that builds character.",
        "The table was a hard place to find traction tonight.",
        "You had to make peace with a session that didn't cooperate.",
        "This one was heavy on the kind of variance that stings.",
        "The runouts wouldn't cooperate tonight.",
        "You ran into a session that didn't want to give you much.",
        "The session gave you more pain than profit.",
        "You had to sit through a lot of tough beats.",
        "The key runouts kept breaking the wrong way.",
        "You got a reminder that not every session can be a win.",
        "The deck was in a punishing mood tonight.",
        "You had to absorb more pain than momentum.",
        "This session was long on frustration and short on momentum.",
        "The pots that could have turned the night kept slipping away.",
        "You ran into the kind of runouts that make you question things.",
        "The session never really gave you a chance to breathe.",
        "You had to make peace with a night that didn't go your way.",
        "The key spots kept going to the other side of the table.",
        "You got a full serving of the game's tougher moments.",
        "The board kept pairing your opponents and not you tonight.",
        "You had to weather a lot of chips going the wrong direction.",
        "This session was a full tour of the downside of variance.",
        "The variance was not in your corner tonight.",
        "You ran into a lineup that wasn't easy to navigate.",
        "The session gave you more setbacks than opportunities.",
        "You had to fold a lot of hands that looked good until the river.",
        "The key hands kept ending in the wrong stack.",
        "You got a concentrated dose of the downside.",
        "The table was a tough place to find an edge tonight.",
        "You had to sit through a lot of runouts that didn't go your way.",
        "This one was a reminder that downswings are part of the deal.",
        "The deck was stubbornly one-sided against you tonight.",
        "You ran into the kind of session that tests your mental game.",
        "The session gave you more red numbers than green.",
        "You had to absorb a lot of the game's tougher variance.",
        "The pots you needed to win kept getting away.",
        "You got a reminder that variance can be brutal.",
        "The runouts were not in your corner tonight.",
        "You had to make peace with a losing session.",
        "This session was heavy on the tuition side of poker.",
        "The table was stingy with its rewards tonight.",
        "You ran into a night that didn't want to give.",
        "The session never really let you get ahead.",
        "You had to watch a lot of good situations go bad.",
        "The key runouts kept landing in the wrong column.",
        "You got a taste of the downside that comes with playing for real.",
        "The deck had other plans tonight.",
        "You had to sit through variance in its rawest form.",
        "This session was long on lessons and short on profit.",
        "The board kept telling you stories you didn't want to hear.",
        "You ran into the kind of night that tests your resolve.",
        "The session gave you more pain than momentum.",
        "You had to make a lot of tough folds that still hurt.",
        "The key pots kept ending in the wrong hands.",
        "You got a full dose of the variance that makes poker hard.",
        "The table was a hard place to find a rhythm tonight.",
        "You had to absorb a session that didn't want to give.",
        "This one was a masterclass in the downside of variance.",
        "The runouts didn't respect your equity tonight.",
        "You ran into a session that refused to cooperate.",
        "The session gave you more bruises than trophies.",
        "You had to sit through more losing results than winning ones.",
        "The key hands kept breaking the wrong way.",
        "You got a reminder that downswings are part of the path.",
        "The deck was not in a giving mood tonight.",
        "You had to weather a lot of runouts that didn't go your way.",
        "This session was a tough reminder that variance is real.",
        "The pots that mattered kept slipping the wrong way.",
        "You ran into the kind of runouts that make the game humbling.",
        "The session never gave you the momentum you needed.",
        "You had to make peace with a night that tested your resolve.",
        "The key runouts kept favoring the other side tonight.",
        "You got a full serving of the game's tougher side.",
        "The table had your number more often than you had theirs.",
        "You had to absorb a lot of chips going the wrong way.",
        "This one was heavy on the kind of variance that doesn't feel fair.",
        "The board kept pairing the wrong hands tonight.",
        "You ran into a night that leaned the wrong way.",
        "The session gave you more pain than profit.",
        "You had to fold more winners than you'd like to admit.",
        "The key spots kept falling the wrong way.",
        "You got a taste of the kind of night that builds character.",
        "The deck was in a punishing mood when you had chips in.",
        "You had to sit through a lot of second-best hands.",
        "This session was long on variance and short on justice.",
        "The runouts kept favoring the other side of the table tonight.",
        "You ran into a session that didn't want to give you much.",
        "The session gave you more setbacks than wins.",
        "You had to make peace with a lot of losing results.",
        "The key hands kept landing in the wrong column.",
        "You got a reminder that not every night can be a winner.",
        "The table was a tough place to find traction tonight.",
        "You had to watch a lot of good equity turn into bad results.",
        "This session was a full serving of negative variance.",
        "The deck was cold when you needed it hot tonight.",
        "You ran into the kind of session that humbles everyone.",
        "The session gave you more red numbers than green.",
        "You had to absorb more losses than wins.",
        "The key runouts kept going the wrong way.",
        "You got a concentrated dose of the game's tougher moments.",
        "The board was unkind more often than not tonight.",
        "You had to sit through a session that didn't cooperate.",
        "This one was a reminder that variance doesn't care about fairness.",
        "The runouts were not in your corner tonight.",
        "You ran into a night that tested your emotional bankroll.",
        "The session gave you more pain than momentum.",
        "You had to make a lot of good folds that still cost you.",
        "The key pots kept ending in the wrong stack.",
        "You got a full dose of the downside of variance.",
        "The deck was not in a generous mood tonight.",
        "You had to weather a lot of runouts that didn't go your way.",
        "This session was heavy on the kind of results that hurt.",
        "The table was stingy with its rewards tonight.",
        "You ran into the kind of runouts that make you sigh.",
        "The session never really let you get comfortable tonight.",
        "You had to make peace with a negative number tonight.",
        "The key hands kept ending in the wrong hands.",
        "You got a reminder that downswings are part of the journey.",
        "The board kept pairing the wrong hands tonight.",
        "You had to sit through more pain than payoff.",
        "This session was a tough way to spend a night.",
        "The variance showed up in its least friendly form tonight.",
        "You ran into a session that refused to give you much.",
        "The session gave you more bruises than wins.",
        "You had to fold more than you'd like and lose more than you wanted.",
        "The key runouts kept favoring the other side tonight.",
        "You got a taste of the downside that comes with the game.",
        "The deck had other plans for you tonight.",
        "You had to absorb a lot of the game's tougher variance.",
        "This one was heavy on the tuition side of the game.",
        "The runouts didn't go your way tonight.",
        "You ran into the kind of night that every player dreads.",
        "The session gave you more pain than profit.",
        "You had to watch your stack shrink more than grow tonight.",
        "The key pots kept slipping the wrong way.",
        "You got a full serving of negative variance tonight.",
        "The table was a hard place to find an edge tonight.",
        "You had to sit through a lot of losing results.",
        "This session was a reminder that variance is real.",
        "The deck was not your friend tonight.",
        "You ran into runouts that didn't respect your equity.",
        "The session gave you more setbacks than opportunities.",
        "You had to make peace with a session that didn't go your way.",
        "The key hands kept breaking the wrong way tonight.",
        "You got a reminder that downswings are part of the path.",
        "The board kept telling you no when you needed yes tonight.",
        "You had to absorb more pain than momentum tonight.",
        "This one was a full tour of the downside of variance.",
        "The runouts were not in your corner tonight.",
        "You ran into a lineup that had your number.",
        "The session gave you more red numbers than green.",
        "You had to sit through variance in its rawest form tonight.",
        "The key runouts kept landing in the wrong column tonight.",
        "You got a concentrated dose of negative variance.",
        "The deck was in a punishing mood tonight.",
        "You had to make peace with a losing session tonight.",
        "This session was long on pain and short on payoff.",
        "The table was a tough place to find a rhythm tonight.",
        "You ran into the kind of session that tests your mental game.",
        "The session gave you more pain than profit.",
        "You had to fold more strong hands than you'd like tonight.",
        "The key spots kept going to the other side of the table tonight.",
        "You got a taste of the downswing that every player knows.",
        "The runouts didn't cooperate tonight.",
        "You had to weather a session that didn't want to give.",
        "This one was a reminder that not every session can be a win.",
        "The deck was cold when it mattered most tonight.",
        "You ran into a night that leaned the wrong way.",
        "The session gave you more lessons than wins.",
        "You had to absorb a lot of chips going the wrong direction tonight.",
        "The key hands kept ending in the wrong stack tonight.",
        "You got a full dose of the variance that makes the game hard.",
        "The board kept pairing your opponents and not you tonight.",
        "You had to sit through a lot of tough beats tonight.",
        "This session was heavy on the kind of variance that stings.",
        "The variance train made a long stop at your seat.",
        "You ran into the kind of runouts that make the game humbling.",
        "The session never really gave you a chance to breathe tonight.",
        "You had to make peace with a night that didn't go your way.",
        "The key pots kept ending in the wrong hands tonight.",
        "You got a reminder that variance doesn't care about your plan.",
        "The deck was not in a giving mood tonight.",
        "You had to watch a lot of good situations go bad tonight.",
        "This one was a masterclass in negative variance.",
        "The runouts seemed to favor everyone else tonight.",
        "You ran into a session that didn't want to cooperate.",
        "The session gave you more pain than momentum tonight.",
        "You had to sit through more setbacks than successes tonight.",
        "The key runouts kept breaking the wrong way tonight.",
        "You got a full serving of the game's tougher side tonight.",
        "The table was stingy with its rewards tonight.",
        "You had to absorb a lot of the game's harder moments tonight.",
        "This session was a tough reminder that variance is real.",
        "The deck had other plans for you tonight.",
        "You ran into a night that tested your resolve.",
        "The session gave you more bruises than wins tonight.",
        "You had to make peace with a negative number tonight.",
        "The key hands kept landing in the wrong column tonight.",
        "You got a taste of the downside that comes with playing for real.",
    ]

    static let negativeClosers: [String] = [
        "The next session is a chance to reset and come back clean.",
        "Your edge doesn't disappear in one night – protect it.",
        "Let this one go and focus on the next hand, the next session.",
        "You're still the same player you were before this session.",
        "The graph will smooth this out over time if you stay disciplined.",
        "Use this as a reason to tighten your process, not your fears.",
        "Tonight was one data point; your sample size is much bigger.",
        "The best response is a good night's sleep and a clear head tomorrow.",
        "You can learn from this without letting it define you.",
        "The long run is still ahead – this is just one mile.",
        "Walk away with your head up and your bankroll management intact.",
        "This session doesn't get to write the story of your career.",
        "Let the sting fade before you draw any big conclusions.",
        "You showed up and played – that still counts for something.",
        "The right move now is to log it, learn, and move on.",
        "Your mental game is more important than this one result.",
        "Treat this as one night in a very long game.",
        "You can turn this into fuel for better preparation.",
        "The next session is a blank slate – use it well.",
        "Don't let one bad night erase the good ones.",
        "You're allowed to feel it and still come back stronger.",
        "The graph has room for nights like this – and for comebacks.",
        "Let this be a reminder to protect your emotional bankroll.",
        "You can absorb this result without letting it own you.",
        "The best players have sessions like this and keep going.",
        "Use this as data, not as a verdict on your skill.",
        "Tonight was rough, but the long run is still yours to shape.",
        "You can recover from this – and you will.",
        "The right response is discipline, not chase.",
        "Let this session go and focus on what you can control.",
        "You're building resilience even when it doesn't feel like it.",
        "The next session doesn't care what happened tonight.",
        "You can turn this frustration into better habits.",
        "Treat yourself with the same patience you'd show a friend.",
        "The loss is real, but so is your capacity to bounce back.",
        "Let this be a lesson in emotional control, not a defeat.",
        "You can walk away with your process intact.",
        "The long-term graph will barely remember this dot.",
        "You're allowed to have bad nights – everyone does.",
        "Use this as a reason to review, not to spiral.",
        "Tonight was one session; your edge is built over thousands.",
        "You can come back stronger if you protect your mindset.",
        "The right move is to rest, reset, and return with focus.",
        "Let this be a reminder that bankroll management exists for nights like this.",
        "You're still in the game – and that's what matters.",
        "You can turn this into a better understanding of variance.",
        "The next session is a chance to prove this was just variance.",
        "Don't add self-tilt to the variance you already took.",
        "You're allowed to be frustrated and still move forward.",
        "The graph will recover if you stay disciplined.",
        "Let this session be a data point, not a defining moment.",
        "You can learn something from this that a winning session can't teach.",
        "The best thing you can do now is close the book on tonight.",
        "You're building the kind of resilience that lasts a lifetime.",
        "Use this as fuel to refine your game, not to punish yourself.",
        "Tonight was tough, but you're tougher.",
        "You can handle this – you've handled worse.",
        "The right response is to protect your confidence and come back fresh.",
        "Let this be a reminder that even the best have nights like this.",
        "You're still the same skilled player – variance just had a say tonight.",
        "You can turn this into a better plan for next time.",
        "The next session is a chance to put this one behind you.",
        "Don't let one bad night shake your belief in your edge.",
        "You're allowed to feel the loss and still believe in the long run.",
        "The graph has room for setbacks – and for comebacks.",
        "Let this be a lesson in walking away with your head up.",
        "You can absorb this and still be a winning player.",
        "The best players use nights like this to get better.",
        "Use this as a reason to tighten your game, not your psyche.",
        "Tonight was one dot on a long line – keep drawing.",
        "You can recover – and the first step is not chasing.",
        "The right move is to log it, learn from it, and let it go.",
        "Let this session remind you why you have a bankroll plan.",
        "You're still building a career – this is one chapter.",
        "You can turn this into better preparation for the next session.",
        "The next session doesn't know what happened tonight.",
        "Don't let one night of variance rewrite your story.",
        "You're allowed to be disappointed and still show up next time.",
        "The long run will smooth this out if you stay the course.",
        "Let this be a reminder that discipline matters most when it's hard.",
        "You can walk away with your process and your self-respect intact.",
        "The loss is temporary; the lessons can be permanent.",
        "Use this as a chance to practice emotional control.",
        "Tonight was a test – and you didn't tilt off.",
        "You can turn this into a sharper game for next time.",
        "The right response is to rest and return with a clear head.",
        "Let this be one low point in a generally rising line.",
        "You're still capable of winning – this was just variance.",
        "You can handle nights like this – that's part of the job.",
        "The next session is a chance to reset and play your best.",
        "Don't add regret to the variance you already absorbed.",
        "You're allowed to feel it – and then let it go.",
        "The graph will forgive this night if you stay disciplined.",
        "Let this session be a reminder to protect your mental game.",
        "You can learn from this without letting it own you.",
        "The best thing you can do now is come back fresh next time.",
        "Use this as data for your review, not for your self-worth.",
        "Tonight was one session in a very long game.",
        "You can turn this into a reason to study and prepare better.",
        "The right move is to close the book and get some rest.",
        "Let this be a reminder that downswings are part of the path.",
        "You're still in the game – and the game is long.",
        "You can absorb this result and still believe in your edge.",
        "The next session is a blank slate – treat it that way.",
        "Don't let one bad night define your relationship with the game.",
        "You're allowed to be human and still be a good player.",
        "The long-term graph will put this night in perspective.",
        "Let this be a lesson in walking away with discipline.",
        "You can turn this into fuel for the next session.",
        "The loss is real, but so is your ability to bounce back.",
        "Use this as a reason to protect your bankroll and your mindset.",
        "Tonight was rough – and you're still here.",
        "You can recover from this by not chasing and coming back fresh.",
        "The right response is to treat yourself with patience.",
        "Let this session be one data point in a long, winning story.",
        "You're still building something – this is just one night.",
        "You can handle this – and you will.",
        "The next session is a chance to prove that variance is variance.",
        "Don't let one night of bad runouts shake your confidence.",
        "You're allowed to feel the sting and still move forward.",
        "The graph has room for nights like this – and for many good ones.",
        "Let this be a reminder that the best response is a disciplined one.",
        "You can walk away with your head up and your process intact.",
        "The best players have sessions like this and keep playing.",
        "Use this as a chance to practice the art of letting go.",
        "Tonight was one dot – your story is much bigger.",
        "You can turn this into a better approach for next time.",
        "The right move now is to rest, reflect, and return stronger.",
        "Let this be a reminder that you're still in the game.",
        "You're still the same player – variance just had a night.",
        "You can turn this into a lesson that makes you stronger.",
        "The next session is waiting – and it doesn't care about tonight.",
        "Don't let one bad session erase your progress.",
        "You're allowed to be frustrated and still believe in yourself.",
        "The long run will remember your discipline more than this result.",
        "Let this session be a reminder that recovery is a skill.",
        "You can absorb this and still be the player you're becoming.",
        "The loss is one night; your edge is built over many.",
        "Use this as fuel to come back with a clear head.",
        "Tonight was a tough mile – the marathon continues.",
        "You can turn this into a reason to protect your mental game.",
        "The right response is to log it, learn, and move on.",
        "Let this be one chapter in a long book – keep writing.",
        "You're still in the game, and that matters more than this one result.",
        "The next session is a chance to reset and come back clean.",
        "Your edge doesn't disappear in one night – protect it.",
        "Let this one go and focus on the next hand, the next session.",
        "You're still the same player you were before this session.",
        "The graph will smooth this out over time if you stay disciplined.",
        "Use this as a reason to tighten your process, not your fears.",
        "Tonight was one data point; your sample size is much bigger.",
        "The best response is a good night's sleep and a clear head tomorrow.",
        "You can learn from this without letting it define you.",
        "The long run is still ahead – this is just one mile.",
        "Walk away with your head up and your bankroll management intact.",
        "This session doesn't get to write the story of your career.",
        "Let the sting fade before you draw any big conclusions.",
        "You showed up and played – that still counts for something.",
        "The right move now is to log it, learn, and move on.",
        "Your mental game is more important than this one result.",
        "Treat this as one night in a very long game.",
        "You can turn this into fuel for better preparation.",
        "The next session is a blank slate – use it well.",
        "Don't let one bad night erase the good ones.",
        "You're allowed to feel it and still come back stronger.",
        "The graph has room for nights like this – and for comebacks.",
        "Let this be a reminder to protect your emotional bankroll.",
        "You can absorb this result without letting it own you.",
        "The best players have sessions like this and keep going.",
        "Use this as data, not as a verdict on your skill.",
        "Tonight was rough, but the long run is still yours to shape.",
        "You can recover from this – and you will.",
        "The right response is discipline, not chase.",
        "Let this session go and focus on what you can control.",
        "You're building resilience even when it doesn't feel like it.",
        "The next session doesn't care what happened tonight.",
        "You can turn this frustration into better habits.",
        "Treat yourself with the same patience you'd show a friend.",
        "The loss is real, but so is your capacity to bounce back.",
        "Let this be a lesson in emotional control, not a defeat.",
        "You can walk away with your process intact.",
        "The long-term graph will barely remember this dot.",
        "You're allowed to have bad nights – everyone does.",
        "Use this as a reason to review, not to spiral.",
        "Tonight was one session; your edge is built over thousands.",
        "You can come back stronger if you protect your mindset.",
        "The right move is to rest, reset, and return with focus.",
        "Let this be a reminder that bankroll management exists for nights like this.",
        "You're still in the game – and that's what matters.",
        "You can turn this into a better understanding of variance.",
        "The next session is a chance to prove this was just variance.",
        "Don't add self-tilt to the variance you already took.",
        "You're allowed to be frustrated and still move forward.",
        "The graph will recover if you stay disciplined.",
        "Let this session be a data point, not a defining moment.",
        "You can learn something from this that a winning session can't teach.",
        "The best thing you can do now is close the book on tonight.",
        "You're building the kind of resilience that lasts a lifetime.",
        "Use this as fuel to refine your game, not to punish yourself.",
        "Tonight was tough, but you're tougher.",
        "You can handle this – you've handled worse.",
        "The right response is to protect your confidence and come back fresh.",
        "Let this be a reminder that even the best have nights like this.",
        "You're still the same skilled player – variance just had a say tonight.",
        "You can turn this into a better plan for next time.",
        "The next session is a chance to put this one behind you.",
        "Don't let one bad night shake your belief in your edge.",
        "You're allowed to feel the loss and still believe in the long run.",
        "The graph has room for setbacks – and for comebacks.",
        "Let this be a lesson in walking away with your head up.",
        "You can absorb this and still be a winning player.",
        "The best players use nights like this to get better.",
        "Use this as a reason to tighten your game, not your psyche.",
        "Tonight was one dot on a long line – keep drawing.",
        "You can recover – and the first step is not chasing.",
        "The right move is to log it, learn from it, and let it go.",
        "Let this session remind you why you have a bankroll plan.",
        "You're still building a career – this is one chapter.",
        "You can turn this into better preparation for the next session.",
        "The next session doesn't know what happened tonight.",
        "Don't let one night of variance rewrite your story.",
        "You're allowed to be disappointed and still show up next time.",
        "The long run will smooth this out if you stay the course.",
        "Let this be a reminder that discipline matters most when it's hard.",
        "You can walk away with your process and your self-respect intact.",
        "The loss is temporary; the lessons can be permanent.",
        "Use this as a chance to practice emotional control.",
        "Tonight was a test – and you didn't tilt off.",
        "You can turn this into a sharper game for next time.",
        "The right response is to rest and return with a clear head.",
        "Let this be one low point in a generally rising line.",
        "You're still capable of winning – this was just variance.",
        "You can handle nights like this – that's part of the job.",
        "The next session is a chance to reset and play your best.",
        "Don't add regret to the variance you already absorbed.",
        "You're allowed to feel it – and then let it go.",
        "The graph will forgive this night if you stay disciplined.",
        "Let this session be a reminder to protect your mental game.",
        "You can learn from this without letting it own you.",
        "The best thing you can do now is come back fresh next time.",
        "Use this as data for your review, not for your self-worth.",
        "Tonight was one session in a very long game.",
        "You can turn this into a reason to study and prepare better.",
        "The right move is to close the book and get some rest.",
        "Let this be a reminder that downswings are part of the path.",
        "You're still in the game – and the game is long.",
        "You can absorb this result and still believe in your edge.",
        "The next session is a blank slate – treat it that way.",
        "Don't let one bad night define your relationship with the game.",
        "You're allowed to be human and still be a good player.",
        "The long-term graph will put this night in perspective.",
        "Let this be a lesson in walking away with discipline.",
        "You can turn this into fuel for the next session.",
        "The loss is real, but so is your ability to bounce back.",
        "Use this as a reason to protect your bankroll and your mindset.",
        "Tonight was rough – and you're still here.",
        "You can recover from this by not chasing and coming back fresh.",
        "The right response is to treat yourself with patience.",
        "Let this session be one data point in a long, winning story.",
        "You're still building something – this is just one night.",
        "You can handle this – and you will.",
        "The next session is a chance to prove that variance is variance.",
        "Don't let one night of bad runouts shake your confidence.",
        "You're allowed to feel the sting and still move forward.",
        "The graph has room for nights like this – and for many good ones.",
        "Let this be a reminder that the best response is a disciplined one.",
        "You can walk away with your head up and your process intact.",
        "The best players have sessions like this and keep playing.",
        "Use this as a chance to practice the art of letting go.",
        "Tonight was one dot – your story is much bigger.",
        "You can turn this into a better approach for next time.",
        "The right move now is to rest, reflect, and return stronger.",
        "Let this be a reminder that you're still in the game.",
        "You're still the same player – variance just had a night.",
        "You can turn this into a lesson that makes you stronger.",
        "The next session is waiting – and it doesn't care about tonight.",
        "Don't let one bad session erase your progress.",
        "You're allowed to be frustrated and still believe in yourself.",
        "The long run will remember your discipline more than this result.",
        "Let this session be a reminder that recovery is a skill.",
        "You can absorb this and still be the player you're becoming.",
        "The loss is one night; your edge is built over many.",
        "Use this as fuel to come back with a clear head.",
        "Tonight was a tough mile – the marathon continues.",
        "You can turn this into a reason to protect your mental game.",
        "The right response is to log it, learn, and move on.",
        "Let this be one chapter in a long book – keep writing.",
        "You're still in the game, and that matters more than this one result.",
    ]
}
